### ISSUE TITLE
文字数が多いとはみ出る

### ISSUE THREAD

**Issue by makotia** [makotia/kanki-time#1]
勝手に改行するか，文字の横幅が画像の横幅を超えたら自動的にフォントサイズを小さくするか．
![01EVKTQWWM4CB2V1K6N13CY2P8](https://user-images.githubusercontent.com/22451396/104094938-5906db80-52d7-11eb-9376-7e04d19b3c39.png)

**Comment by 0x307e** [comment]
まあ仕方ない
